export const products = [
	{
		id: '1',
		title: 'Брошь Котик',
		price: 15,
		image: '/img/brooch-1.jpg',
		category: 'brooches',
		tags: ['животные', 'котик'],
	},
	{
		id: '2',
		title: 'Брошь Цветок',
		price: 18,
		image: '/img/brooch-2.jpg',
		category: 'brooches',
		tags: ['цветы', 'лето'],
	},
	{
		id: '3',
		title: 'Брошь Листик',
		price: 12,
		image: '/img/brooch-3.jpg',
		category: 'brooches',
		tags: ['лист', 'природа'],
	},
	{
		id: '4',
		title: 'Брошь Птичка',
		price: 17,
		image: '/img/brooch-4.jpg',
		category: 'brooches',
		tags: ['животные', 'птица'],
	},
	{
		id: '5',
		title: 'Брошь Сердце',
		price: 14,
		image: '/img/brooch-5.jpg',
		category: 'brooches',
		tags: ['любовь', 'романтика'],
	},
	{
		id: '6',
		title: 'Брошь Звезда',
		price: 20,
		image: '/img/brooch-6.jpg',
		category: 'brooches',
		tags: ['космос', 'звезда'],
	},
	{
		id: '7',
		title: 'Брошь Бабочка',
		price: 16,
		image: '/img/brooch-7.jpg',
		category: 'brooches',
		tags: ['животные', 'бабочка'],
	},
	{
		id: '8',
		title: 'Брошь Морская раковина',
		price: 19,
		image: '/img/brooch-8.jpg',
		category: 'brooches',
		tags: ['море', 'путешествия'],
	},
	{
		id: '9',
		title: 'Брошь Луна',
		price: 22,
		image: '/img/brooch-9.jpg',
		category: 'brooches',
		tags: ['космос', 'луна'],
	},
	{
		id: '10',
		title: 'Брошь Волна',
		price: 15,
		image: '/img/brooch-10.jpg',
		category: 'brooches',
		tags: ['море', 'волна'],
	},
	{
		id: '11',
		title: 'Брошь Сова',
		price: 18,
		image: '/img/brooch-11.jpg',
		category: 'brooches',
		tags: ['животные', 'сова'],
	},
	{
		id: '12',
		title: 'Брошь Листья',
		price: 14,
		image: '/img/brooch-12.jpg',
		category: 'brooches',
		tags: ['природа', 'лист'],
	},
	{
		id: '13',
		title: 'Брошь Цветок Лотоса',
		price: 20,
		image: '/img/brooch-13.jpg',
		category: 'brooches',
		tags: ['цветы', 'лотос'],
	},
	{
		id: '14',
		title: 'Брошь Кленовый лист',
		price: 17,
		image: '/img/brooch-14.jpg',
		category: 'brooches',
		tags: ['лист', 'природа'],
	},
	{
		id: '15',
		title: 'Брошь Яблоко',
		price: 13,
		image: '/img/brooch-15.jpg',
		category: 'brooches',
		tags: ['фрукты', 'еда'],
	},
	{
		id: '16',
		title: 'Брошь Листья Осени',
		price: 16,
		image: '/img/brooch-16.jpg',
		category: 'brooches',
		tags: ['осень', 'природа'],
	},
	{
		id: '17',
		title: 'Брошь Серебряная Звезда',
		price: 21,
		image: '/img/brooch-17.jpg',
		category: 'brooches',
		tags: ['звезда', 'космос'],
	},
	{
		id: '18',
		title: 'Брошь Роза',
		price: 19,
		image: '/img/brooch-18.jpg',
		category: 'brooches',
		tags: ['цветы', 'любовь'],
	},
	{
		id: '19',
		title: 'Брошь Панда',
		price: 18,
		image: '/img/brooch-19.jpg',
		category: 'brooches',
		tags: ['животные', 'панда'],
	},
	{
		id: '20',
		title: 'Брошь Котёнок',
		price: 15,
		image: '/img/brooch-20.jpg',
		category: 'brooches',
		tags: ['животные', 'котик'],
	},
	{
		id: '21',
		title: 'Брошь Листок Папоротника',
		price: 16,
		image: '/img/brooch-21.jpg',
		category: 'brooches',
		tags: ['лист', 'природа'],
	},
	{
		id: '22',
		title: 'Брошь Фея',
		price: 23,
		image: '/img/brooch-22.jpg',
		category: 'brooches',
		tags: ['фэнтези', 'волшебство'],
	},
]
